-- ===================================================
-- Emisión de recibos y rendición de cobradores
-- ===================================================
-- Circuito:
--   1. Se EMITE una planilla para un cobrador y/o zona y un rango de fechas: un
--      recibo por cada cuota impaga que vence en ese lapso.
--   2. El cobrador sale con los recibos impresos y anota a mano lo que cobra.
--   3. Al volver se RINDE la planilla: se carga lo cobrado en cada recibo y el
--      sistema registra los pagos contra cada cuota, todo en una transacción.
--
-- Los datos del recibo se guardan como FOTO al momento de emitir: una
-- reimpresión tiene que salir idéntica a la que se entregó, aunque después se
-- hayan registrado pagos.

-- ---------------------------------------------------------------------------
-- 1. Número de cliente (el "CLIENTE N°" del recibo)
-- ---------------------------------------------------------------------------
-- Es editable a propósito: permite conservar la numeración que ya se usaba en
-- papel. Si se deja vacío, se asigna el siguiente libre.
alter table public.clients add column if not exists numero integer;

with ordenados as (
    select id, row_number() over (order by created_at, id) as n
    from public.clients
    where numero is null
)
update public.clients c
set numero = o.n + coalesce((select max(numero) from public.clients), 0)
from ordenados o
where c.id = o.id;

alter table public.clients alter column numero set not null;

alter table public.clients drop constraint if exists clients_numero_key;
alter table public.clients add  constraint clients_numero_key unique (numero);

alter table public.clients drop constraint if exists clients_numero_positivo;
alter table public.clients add  constraint clients_numero_positivo check (numero > 0);

create or replace function public.assign_client_numero()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    if new.numero is null then
        -- Serializa las altas simultáneas para que no salgan dos con el mismo número
        perform pg_advisory_xact_lock(hashtext('public.clients.numero'));
        select coalesce(max(numero), 0) + 1 into new.numero from public.clients;
    end if;
    return new;
end;
$$;

drop trigger if exists clients_assign_numero on public.clients;
create trigger clients_assign_numero
    before insert on public.clients
    for each row
    execute function public.assign_client_numero();

-- ---------------------------------------------------------------------------
-- 1b. Fecha de otorgamiento del préstamo (la "FECHA EMISIÓN" del recibo)
-- ---------------------------------------------------------------------------
-- No alcanza con created_at: al pasar al sistema préstamos que ya estaban en la
-- calle, la fecha de carga no es la fecha en que se entregó la plata.
alter table public.loans add column if not exists fecha_otorgamiento date;
update public.loans set fecha_otorgamiento = created_at::date where fecha_otorgamiento is null;
alter table public.loans alter column fecha_otorgamiento set default current_date;
alter table public.loans alter column fecha_otorgamiento set not null;

-- ---------------------------------------------------------------------------
-- 2. Planillas de rendición
-- ---------------------------------------------------------------------------
create table if not exists public.rendiciones (
    id                uuid primary key default gen_random_uuid(),
    numero            integer generated by default as identity unique,
    -- Filtros con los que se emitió (texto: es un registro histórico)
    cobrador          varchar(150),
    zona              varchar(100),
    desde             date not null,
    hasta             date not null check (hasta >= desde),
    incluye_vencidas  boolean not null default false,
    estado            varchar(20) not null default 'emitida'
                      check (estado in ('emitida', 'rendida')),
    fecha_emision     timestamptz not null default now(),
    fecha_rendicion   date,
    cantidad_recibos  integer not null default 0,
    total_esperado    numeric(12, 2) not null default 0,
    total_cobrado     numeric(12, 2),
    observaciones     text,
    created_at        timestamptz not null default now()
);

create index if not exists rendiciones_estado_idx   on public.rendiciones (estado);
create index if not exists rendiciones_cobrador_idx on public.rendiciones (cobrador);

-- ---------------------------------------------------------------------------
-- 3. Recibos (uno por cuota), con la foto de los datos al emitir
-- ---------------------------------------------------------------------------
create table if not exists public.rendicion_items (
    id                 uuid primary key default gen_random_uuid(),
    rendicion_id       uuid not null references public.rendiciones (id) on delete cascade,
    numero_recibo      integer not null,
    installment_id     uuid references public.installments (id) on delete set null,
    loan_id            uuid references public.loans (id) on delete set null,
    client_id          uuid references public.clients (id) on delete set null,

    -- Cliente
    cliente_numero     integer,
    cliente_nombre     text not null,
    domicilio          text,
    telefono           text,
    rubro              text,
    zona               text,
    cobrador           text,

    -- Préstamo
    credito_numero     integer not null default 0,
    fecha_otorgamiento date,
    cuotas_total       integer,
    valor_cuota        numeric(12, 2),
    prestamo_total     numeric(12, 2),
    prestamo_pagado    numeric(12, 2),
    prestamo_saldo     numeric(12, 2),
    ultimo_pago        date,
    atraso             numeric(12, 2) not null default 0,

    -- Cuota a cobrar
    cuota_numero       integer,
    vencimiento        date,
    importe            numeric(12, 2) not null,

    -- Resultado de la rendición
    monto_cobrado      numeric(12, 2) check (monto_cobrado >= 0),
    payment_id         uuid references public.payments (id) on delete set null,

    unique (rendicion_id, numero_recibo)
);

create index if not exists rendicion_items_rendicion_idx   on public.rendicion_items (rendicion_id);
create index if not exists rendicion_items_installment_idx on public.rendicion_items (installment_id);

-- Una planilla rendida ya generó pagos: no se puede borrar sin descuadrar la caja.
create or replace function public.prevent_delete_rendida()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
    if old.estado = 'rendida' then
        raise exception 'La planilla N° % ya fue rendida y no se puede anular.', old.numero;
    end if;
    return old;
end;
$$;

drop trigger if exists rendiciones_prevent_delete on public.rendiciones;
create trigger rendiciones_prevent_delete
    before delete on public.rendiciones
    for each row
    execute function public.prevent_delete_rendida();

-- ---------------------------------------------------------------------------
-- 4. Emitir: arma la planilla y sus recibos en una sola transacción
-- ---------------------------------------------------------------------------
create or replace function public.emitir_rendicion(
    p_desde            date,
    p_hasta            date,
    p_cobrador         text    default null,
    p_zona             text    default null,
    p_incluir_vencidas boolean default false
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_id       uuid;
    v_cantidad integer;
    v_total    numeric(12, 2);
begin
    p_cobrador := nullif(trim(p_cobrador), '');
    p_zona     := nullif(trim(p_zona), '');

    if p_desde is null or p_hasta is null then
        raise exception 'Indicá el rango de fechas a emitir.';
    end if;
    if p_hasta < p_desde then
        raise exception 'La fecha "hasta" no puede ser anterior a "desde".';
    end if;

    insert into public.rendiciones (cobrador, zona, desde, hasta, incluye_vencidas)
    values (p_cobrador, p_zona, p_desde, p_hasta, p_incluir_vencidas)
    returning id into v_id;

    insert into public.rendicion_items (
        rendicion_id, numero_recibo, installment_id, loan_id, client_id,
        cliente_numero, cliente_nombre, domicilio, telefono, rubro, zona, cobrador,
        credito_numero, fecha_otorgamiento, cuotas_total, valor_cuota,
        prestamo_total, prestamo_pagado, prestamo_saldo, ultimo_pago, atraso,
        cuota_numero, vencimiento, importe
    )
    select
        v_id,
        row_number() over (order by c.zona nulls last, c.numero, i.due_date),
        i.id, l.id, c.id,
        c.numero, c.name, c.address, c.phone, c.rubro, c.zona,
        coalesce(l.cobrador, c.cobrador),
        cred.anteriores,
        l.fecha_otorgamiento,
        l.installments_count,
        l.installment_amount,
        l.total_amount,
        agg.pagado,
        l.total_amount - agg.pagado,
        up.ultimo,
        agg.atraso,
        i.number,
        i.due_date,
        i.amount - i.paid_amount
    from public.installments i
    join public.loans   l on l.id = i.loan_id
    join public.clients c on c.id = l.client_id
    cross join lateral (
        select coalesce(sum(i2.paid_amount), 0) as pagado,
               coalesce(sum(i2.amount - i2.paid_amount)
                        filter (where i2.due_date < current_date and i2.paid_amount < i2.amount), 0) as atraso
        from public.installments i2
        where i2.loan_id = l.id
    ) agg
    cross join lateral (
        select max(p.paid_at) as ultimo
        from public.payments p
        where p.loan_id = l.id
    ) up
    cross join lateral (
        -- N° de crédito del cliente: 0 el primero, 1 el segundo... (el "/0" del papel)
        select count(*)::integer as anteriores
        from public.loans l2
        where l2.client_id = l.client_id
          and (l2.fecha_otorgamiento, l2.created_at, l2.id)
            < (l.fecha_otorgamiento, l.created_at, l.id)
    ) cred
    where l.status = 'active'
      and i.paid_amount < i.amount
      and i.due_date <= p_hasta
      and (p_incluir_vencidas or i.due_date >= p_desde)
      and (p_cobrador is null or coalesce(l.cobrador, c.cobrador) = p_cobrador)
      and (p_zona is null or c.zona = p_zona)
      -- Una cuota que ya salió en otra planilla todavía sin rendir no se reimprime
      and not exists (
          select 1
          from public.rendicion_items ri
          join public.rendiciones r on r.id = ri.rendicion_id
          where ri.installment_id = i.id
            and r.estado = 'emitida'
            and r.id <> v_id
      );

    select count(*), coalesce(sum(importe), 0)
    into v_cantidad, v_total
    from public.rendicion_items
    where rendicion_id = v_id;

    if v_cantidad = 0 then
        -- La excepción deshace también el alta de la planilla vacía
        raise exception 'No hay cuotas pendientes para emitir con esos filtros.';
    end if;

    update public.rendiciones
    set cantidad_recibos = v_cantidad,
        total_esperado   = v_total
    where id = v_id;

    return v_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- 5. Rendir: registra los cobros de toda la planilla en una sola transacción
-- ---------------------------------------------------------------------------
-- p_montos: objeto JSON { "<id del recibo>": monto_cobrado, ... }.
-- Los recibos que no figuran se toman como no cobrados (0).
create or replace function public.rendir_rendicion(
    p_rendicion_id uuid,
    p_montos       jsonb,
    p_fecha        date default current_date
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
    v_rend  public.rendiciones%rowtype;
    v_item  public.rendicion_items%rowtype;
    v_monto numeric(12, 2);
    v_pago  uuid;
    v_total numeric(12, 2) := 0;
begin
    select * into v_rend
    from public.rendiciones
    where id = p_rendicion_id
    for update;

    if not found then
        raise exception 'La planilla no existe.';
    end if;
    if v_rend.estado <> 'emitida' then
        raise exception 'La planilla N° % ya fue rendida.', v_rend.numero;
    end if;

    for v_item in
        select * from public.rendicion_items
        where rendicion_id = p_rendicion_id
        order by numero_recibo
    loop
        v_monto := coalesce((p_montos ->> v_item.id::text)::numeric, 0);

        if v_monto < 0 then
            raise exception 'El recibo % tiene un monto negativo.', v_item.numero_recibo;
        end if;

        v_pago := null;
        if v_monto > 0 and v_item.installment_id is not null and v_item.loan_id is not null then
            insert into public.payments (loan_id, installment_id, amount, paid_at, cobrador, method, notes)
            values (
                v_item.loan_id,
                v_item.installment_id,
                v_monto,
                coalesce(p_fecha, current_date),
                coalesce(v_item.cobrador, v_rend.cobrador),
                'cash',
                'Planilla N° ' || v_rend.numero || ' - recibo ' || v_item.numero_recibo
            )
            returning id into v_pago;
        end if;

        update public.rendicion_items
        set monto_cobrado = v_monto,
            payment_id    = v_pago
        where id = v_item.id;

        v_total := v_total + v_monto;
    end loop;

    update public.rendiciones
    set estado          = 'rendida',
        fecha_rendicion = coalesce(p_fecha, current_date),
        total_cobrado   = v_total
    where id = p_rendicion_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- 6. RLS y policies de desarrollo
-- ---------------------------------------------------------------------------
alter table public.rendiciones     enable row level security;
alter table public.rendicion_items enable row level security;

drop policy if exists "dev_full_access_rendiciones"     on public.rendiciones;
drop policy if exists "dev_full_access_rendicion_items" on public.rendicion_items;

create policy "dev_full_access_rendiciones"
    on public.rendiciones for all to anon, authenticated
    using (true) with check (true);

create policy "dev_full_access_rendicion_items"
    on public.rendicion_items for all to anon, authenticated
    using (true) with check (true);
